In [2]:
from google.colab import files

uploaded = files.upload()

Saving retail_store_sales.csv to retail_store_sales.csv

In [3]:
import pandas as pd

In [4]:
# Load Dataset
df = pd.read_csv("retail_store_sales.csv")

In [5]:
# Understanding Dataset
print(df.info)

<bound method DataFrame.info of       Transaction ID Customer ID       Category          Item  Price Per Unit  \
0        TXN_6867343     CUST_09     Patisserie   Item_10_PAT            18.5
1        TXN_3731986     CUST_22  Milk Products  Item_17_MILK            29.0
2        TXN_9303719     CUST_02       Butchers   Item_12_BUT            21.5
3        TXN_9458126     CUST_06      Beverages   Item_16_BEV            27.5
4        TXN_4575373     CUST_05           Food   Item_6_FOOD            12.5
...              ...         ...            ...           ...             ...
12570    TXN_9347481     CUST_18     Patisserie   Item_23_PAT            38.0
12571    TXN_4009414     CUST_03      Beverages    Item_2_BEV             6.5
12572    TXN_5306010     CUST_11       Butchers    Item_7_BUT            14.0
12573    TXN_5167298     CUST_04      Furniture    Item_7_FUR            14.0
12574    TXN_2407494     CUST_23           Food   Item_9_FOOD            17.0

       Quantity  Total Spent  Payment Method  Location Transaction Date  \
0          10.0        185.0  Digital Wallet    Online       2024-04-08
1           9.0        261.0  Digital Wallet    Online       2023-07-23
2           2.0         43.0     Credit Card    Online       2022-10-05
3           9.0        247.5     Credit Card    Online       2022-05-07
4           7.0         87.5  Digital Wallet    Online       2022-10-02
...         ...          ...             ...       ...              ...
12570       4.0        152.0     Credit Card  In-store       2023-09-03
12571       9.0         58.5            Cash    Online       2022-08-12
12572      10.0        140.0            Cash    Online       2024-08-24
12573       6.0         84.0            Cash    Online       2023-12-30
12574       3.0         51.0            Cash    Online       2022-08-06

      Discount Applied
0                 True
1                 True
2                False
3                  NaN
4                False
...                ...
12570              NaN
12571            False
12572              NaN
12573             True
12574              NaN

[12575 rows x 11 columns]>

In [6]:
print(df.describe)

<bound method NDFrame.describe of       Transaction ID Customer ID       Category          Item  Price Per Unit  \
0        TXN_6867343     CUST_09     Patisserie   Item_10_PAT            18.5
1        TXN_3731986     CUST_22  Milk Products  Item_17_MILK            29.0
2        TXN_9303719     CUST_02       Butchers   Item_12_BUT            21.5
3        TXN_9458126     CUST_06      Beverages   Item_16_BEV            27.5
4        TXN_4575373     CUST_05           Food   Item_6_FOOD            12.5
...              ...         ...            ...           ...             ...
12570    TXN_9347481     CUST_18     Patisserie   Item_23_PAT            38.0
12571    TXN_4009414     CUST_03      Beverages    Item_2_BEV             6.5
12572    TXN_5306010     CUST_11       Butchers    Item_7_BUT            14.0
12573    TXN_5167298     CUST_04      Furniture    Item_7_FUR            14.0
12574    TXN_2407494     CUST_23           Food   Item_9_FOOD            17.0

       Quantity  Total Spent  Payment Method  Location Transaction Date  \
0          10.0        185.0  Digital Wallet    Online       2024-04-08
1           9.0        261.0  Digital Wallet    Online       2023-07-23
2           2.0         43.0     Credit Card    Online       2022-10-05
3           9.0        247.5     Credit Card    Online       2022-05-07
4           7.0         87.5  Digital Wallet    Online       2022-10-02
...         ...          ...             ...       ...              ...
12570       4.0        152.0     Credit Card  In-store       2023-09-03
12571       9.0         58.5            Cash    Online       2022-08-12
12572      10.0        140.0            Cash    Online       2024-08-24
12573       6.0         84.0            Cash    Online       2023-12-30
12574       3.0         51.0            Cash    Online       2022-08-06

      Discount Applied
0                 True
1                 True
2                False
3                  NaN
4                False
...                ...
12570              NaN
12571            False
12572              NaN
12573             True
12574              NaN

[12575 rows x 11 columns]>

In [7]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [8]:
print(df.drop_duplicates)

<bound method DataFrame.drop_duplicates of       Transaction ID Customer ID       Category          Item  Price Per Unit  \
0        TXN_6867343     CUST_09     Patisserie   Item_10_PAT            18.5
1        TXN_3731986     CUST_22  Milk Products  Item_17_MILK            29.0
2        TXN_9303719     CUST_02       Butchers   Item_12_BUT            21.5
3        TXN_9458126     CUST_06      Beverages   Item_16_BEV            27.5
4        TXN_4575373     CUST_05           Food   Item_6_FOOD            12.5
...              ...         ...            ...           ...             ...
12570    TXN_9347481     CUST_18     Patisserie   Item_23_PAT            38.0
12571    TXN_4009414     CUST_03      Beverages    Item_2_BEV             6.5
12572    TXN_5306010     CUST_11       Butchers    Item_7_BUT            14.0
12573    TXN_5167298     CUST_04      Furniture    Item_7_FUR            14.0
12574    TXN_2407494     CUST_23           Food   Item_9_FOOD            17.0

       Quantity  Total Spent  Payment Method  Location Transaction Date  \
0          10.0        185.0  Digital Wallet    Online       2024-04-08
1           9.0        261.0  Digital Wallet    Online       2023-07-23
2           2.0         43.0     Credit Card    Online       2022-10-05
3           9.0        247.5     Credit Card    Online       2022-05-07
4           7.0         87.5  Digital Wallet    Online       2022-10-02
...         ...          ...             ...       ...              ...
12570       4.0        152.0     Credit Card  In-store       2023-09-03
12571       9.0         58.5            Cash    Online       2022-08-12
12572      10.0        140.0            Cash    Online       2024-08-24
12573       6.0         84.0            Cash    Online       2023-12-30
12574       3.0         51.0            Cash    Online       2022-08-06

      Discount Applied
0                 True
1                 True
2                False
3                  NaN
4                False
...                ...
12570              NaN
12571            False
12572              NaN
12573             True
12574              NaN

[12575 rows x 11 columns]>

In [9]:
df[df.duplicated]

Empty DataFrame
Columns: [Transaction ID, Customer ID, Category, Item, Price Per Unit, Quantity, Total Spent, Payment Method, Location, Transaction Date, Discount Applied]
Index: []

In [10]:
df.dtypes

Transaction ID       object
Customer ID          object
Category             object
Item                 object
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
Discount Applied     object
dtype: object

In [11]:
df.columns

Index(['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit',
       'Quantity', 'Total Spent', 'Payment Method', 'Location',
       'Transaction Date', 'Discount Applied'],
      dtype='object')

In [12]:
df.shape

(12575, 11)

In [13]:
# Data Cleaning
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [14]:
df.dropna(subset='Item',inplace=True)

In [15]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                   0
Price Per Unit         0
Quantity               0
Total Spent            0
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    3783
dtype: int64

In [16]:
df['Discount Applied'].fillna(df['Discount Applied'].mode()[0],inplace=True)

/tmp/ipykernel_3978/3604058853.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Discount Applied'].fillna(df['Discount Applied'].mode()[0],inplace=True)
/tmp/ipykernel_3978/3604058853.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Discount Applied'].fillna(df['Discount Applied'].mode()[0],inplace=True)

In [17]:
df.isnull().sum()

Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

In [18]:
df

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,True
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,True
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,True
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,True

In [19]:
df.columns

Index(['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit',
       'Quantity', 'Total Spent', 'Payment Method', 'Location',
       'Transaction Date', 'Discount Applied'],
      dtype='object')

In [20]:
df.columns.str.lower()

Index(['transaction id', 'customer id', 'category', 'item', 'price per unit',
       'quantity', 'total spent', 'payment method', 'location',
       'transaction date', 'discount applied'],
      dtype='object')

In [21]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

In [22]:
df

,transaction_id,customer_id,category,item,price_per_unit,quantity,total_spent,payment_method,location,transaction_date,discount_applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,True
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,True
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,True
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,True

In [23]:
# EDA
high_sales = df.groupby('category')['total_spent'].sum()
sort_sales = high_sales.sort_values(ascending = False)
print(sort_sales)

category
Butchers                              197426.0
Electric household essentials         192441.5
Beverages                             187978.5
Furniture                             186527.0
Food                                  184645.0
Computers and electric accessories    180902.5
Patisserie                            172330.5
Milk Products                         170747.5
Name: total_spent, dtype: float64

In [24]:
df.groupby('category')['total_spent'].nunique().sort_values(ascending=False)

category
Patisserie                            221
Computers and electric accessories    219
Food                                  218
Butchers                              218
Beverages                             217
Electric household essentials         215
Furniture                             214
Milk Products                         207
Name: total_spent, dtype: int64

In [25]:
print(df['total_spent'].mean())

129.64253652525963

In [26]:
df.groupby('customer_id')['total_spent'].nunique().sort_values(ascending=False)

customer_id
CUST_05    200
CUST_24    199
CUST_16    198
CUST_23    198
CUST_15    197
CUST_02    195
CUST_11    195
CUST_20    195
CUST_06    194
CUST_18    194
CUST_12    193
CUST_13    193
CUST_09    192
CUST_04    192
CUST_22    191
CUST_10    191
CUST_08    191
CUST_01    190
CUST_25    189
CUST_21    188
CUST_19    188
CUST_07    187
CUST_03    185
CUST_14    182
CUST_17    180
Name: total_spent, dtype: int64

In [27]:
df.groupby('transaction_id')['quantity'].mean()

transaction_id
TXN_1002182     5.0
TXN_1003865     5.0
TXN_1003940     9.0
TXN_1004091     3.0
TXN_1004124     5.0
               ...
TXN_9996492     8.0
TXN_9996909    10.0
TXN_9997234     8.0
TXN_9998575     9.0
TXN_9999729     5.0
Name: quantity, Length: 11362, dtype: float64

In [28]:
df["transaction_date"] = pd.to_datetime( df["transaction_date"])

In [29]:
df['month'] = df['transaction_date'].dt.month

In [30]:
df['year'] = df['transaction_date'].dt.year

In [31]:
df['day'] = df['transaction_date'].dt.day

In [32]:
df

,transaction_id,customer_id,category,item,price_per_unit,quantity,total_spent,payment_method,location,transaction_date,discount_applied,month,year,day
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,4,2024,8
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,7,2023,23
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,10,2022,5
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,True,5,2022,7
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,10,2022,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,True,9,2023,3
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False,8,2022,12
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,True,8,2024,24
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True,12,2023,30
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,True,8,2022,6

In [33]:
df.groupby('month')['total_spent'].sum().sort_values(ascending=False)

month
1     165611.0
7     124328.5
6     123969.0
12    123588.0
9     122256.0
5     119569.5
4     118933.5
8     116875.5
11    116256.5
3     115386.0
2     113153.5
10    113071.5
Name: total_spent, dtype: float64

In [37]:
df.groupby('day')['total_spent'].sum().sort_values(ascending=False)

day
2     54430.0
1     54138.0
18    54077.5
22    53302.0
12    52310.5
10    51879.0
8     51109.0
9     50308.5
13    50100.0
28    50009.5
14    49489.5
25    49270.0
24    48941.5
21    47871.5
4     47711.0
7     47672.0
16    47619.0
3     47521.5
27    47380.5
20    47039.5
23    46889.0
15    46339.5
29    46302.0
17    45722.0
11    43776.5
19    43676.0
30    43445.5
6     42621.0
5     42058.5
26    41079.0
31    28909.5
Name: total_spent, dtype: float64

In [38]:
df.groupby('quantity')['total_spent'].sum()

quantity
1.0      25341.0
2.0      50437.0
3.0      80208.0
4.0     104078.0
5.0     138902.5
6.0     163737.0
7.0     188716.5
8.0     214788.0
9.0     225760.5
10.0    281030.0
Name: total_spent, dtype: float64

In [39]:
df.groupby('item')['total_spent'].sum().sort_values(ascending=False)

item
Item_25_FUR     25256.0
Item_25_EHE     23083.0
Item_25_BUT     21894.0
Item_24_FUR     21172.0
Item_25_FOOD    20541.0
                 ...
Item_1_FOOD       675.0
Item_1_CEA        630.0
Item_4_CEA        570.0
Item_5_BEV        517.0
Item_3_EHE        224.0
Name: total_spent, Length: 200, dtype: float64

In [45]:
# Feature Engineering
df['total_sales'] = df['total_spent']

In [42]:
df['day_of_week'] = df['transaction_date'].dt.day_name()

In [46]:
df['average_order_value'] = df['total_sales'].mean()

In [47]:
df['customer_total_spending'] = df.groupby('customer_id')['total_sales'].transform('sum')

In [53]:
df

,transaction_id,customer_id,category,item,price_per_unit,quantity,total_spent,payment_method,location,transaction_date,discount_applied,month,year,day,Total_Sales,day_of_week,total_Sales,total_sales,average_order_value,customer_total_spending
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,4,2024,8,185.0,Monday,185.0,185.0,129.642537,57113.0
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,7,2023,23,261.0,Sunday,261.0,261.0,129.642537,59460.0
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,10,2022,5,43.0,Wednesday,43.0,43.0,129.642537,59512.5
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,True,5,2022,7,247.5,Saturday,247.5,247.5,129.642537,56020.0
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,10,2022,2,87.5,Sunday,87.5,87.5,129.642537,63855.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,True,9,2023,3,152.0,Sunday,152.0,152.0,129.642537,55454.5
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False,8,2022,12,58.5,Friday,58.5,58.5,129.642537,57150.0
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,True,8,2024,24,140.0,Saturday,140.0,140.0,129.642537,57449.5
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True,12,2023,30,84.0,Saturday,84.0,84.0,129.642537,57959.0
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,True,8,2022,6,51.0,Saturday,51.0,51.0,129.642537,59738.5

In [54]:
df.drop(columns=['Total_Sales', 'total_Sales'], inplace=True)

In [55]:
df.columns

Index(['transaction_id', 'customer_id', 'category', 'item', 'price_per_unit',
       'quantity', 'total_spent', 'payment_method', 'location',
       'transaction_date', 'discount_applied', 'month', 'year', 'day',
       'day_of_week', 'total_sales', 'average_order_value',
       'customer_total_spending'],
      dtype='object')

In [56]:
df

,transaction_id,customer_id,category,item,price_per_unit,quantity,total_spent,payment_method,location,transaction_date,discount_applied,month,year,day,day_of_week,total_sales,average_order_value,customer_total_spending
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,4,2024,8,Monday,185.0,129.642537,57113.0
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,7,2023,23,Sunday,261.0,129.642537,59460.0
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,10,2022,5,Wednesday,43.0,129.642537,59512.5
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,True,5,2022,7,Saturday,247.5,129.642537,56020.0
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,10,2022,2,Sunday,87.5,129.642537,63855.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,True,9,2023,3,Sunday,152.0,129.642537,55454.5
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False,8,2022,12,Friday,58.5,129.642537,57150.0
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,True,8,2024,24,Saturday,140.0,129.642537,57449.5
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True,12,2023,30,Saturday,84.0,129.642537,57959.0
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,True,8,2022,6,Saturday,51.0,129.642537,59738.5